org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-factory-blocks
addon_name=BlueMap Factory Blocks Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-factory-blocks-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=86501
accepted_jar_sha256=69f4f53022aac455a4bcc362dc09cbaf5b3f73cf108ccc154dffa8e238869302
accepted_sources_jar_size=51485
accepted_sources_jar_sha256=c94167752f16ddc6b5f3bf9c711ca719dcedb1a9bb437fc8b9e65f3149072613
accepted_pom_size=1373
accepted_pom_sha256=eb1a67ad49ba54f28ea28fa10966fc30f1913f294ef20c861881596247b6f300
accepted_module_size=2866
accepted_module_sha256=14cb9927206ce573f4af4306adced9e2167c9194402131973629cc4a7b2479bb
