org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-factory-blocks
addon_name=BlueMap Factory Blocks Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-factory-blocks-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=90486
accepted_jar_sha256=bfa0c9aa6a96425fa62a5acf3a4a4e5c212e6537378da5bc8e1f59c19d09b0a0
accepted_sources_jar_size=55073
accepted_sources_jar_sha256=892c0ea95d8d203065f037a7f40c56600393e9ca911ae0e59ab1aaa31f84b346
accepted_pom_size=1373
accepted_pom_sha256=aaab32190aed8ef26d1a360a8cedf46550d1d06ce3b3f49f7ae0535ab00ccbfd
accepted_module_size=2866
accepted_module_sha256=42833f27034c316b54abe4a96293adf4ecb50064db199b843c4f98449ea62cbf
