#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the bounded Factory Blocks staging gallery."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent
NAMESPACE = "factory_blocks_gallery"
OBJECTIVE = "fb_gallery"
ENVELOPE = {
    "min_x": 160,
    "max_x": 223,
    "min_y": 99,
    "max_y": 124,
    "min_z": 160,
    "max_z": 191,
}
PAD = (160, 99, 160, 211, 99, 168)

# Section, label, x, y, z, exact property-free block ID.
PLACEMENTS = (
    ("A", "isolated factory", 164, 100, 164, "factory_blocks:factory"),
    ("A", "factory wall lower-left", 168, 100, 164, "factory_blocks:factory"),
    ("A", "factory wall lower-edge", 169, 100, 164, "factory_blocks:factory"),
    ("A", "factory wall lower-right", 170, 100, 164, "factory_blocks:factory"),
    ("A", "factory wall left-edge", 168, 101, 164, "factory_blocks:factory"),
    ("A", "factory wall center", 169, 101, 164, "factory_blocks:factory"),
    ("A", "factory wall right-edge", 170, 101, 164, "factory_blocks:factory"),
    ("A", "factory wall upper-left", 168, 102, 164, "factory_blocks:factory"),
    ("A", "factory wall upper-edge", 169, 102, 164, "factory_blocks:factory"),
    ("A", "factory wall upper-right", 170, 102, 164, "factory_blocks:factory"),
    ("B", "hex south role 1", 180, 102, 164, "factory_blocks:hex"),
    ("B", "hex south role 2", 181, 102, 164, "factory_blocks:hex"),
    ("B", "hex south role 3", 182, 102, 164, "factory_blocks:hex"),
    ("B", "hex south role 4", 180, 103, 164, "factory_blocks:hex"),
    ("B", "hex south role 5", 181, 103, 164, "factory_blocks:hex"),
    ("B", "hex south role 6", 182, 103, 164, "factory_blocks:hex"),
    ("B", "hex south role 7", 180, 104, 164, "factory_blocks:hex"),
    ("B", "hex south role 8", 181, 104, 164, "factory_blocks:hex"),
    ("B", "hex south role 9", 182, 104, 164, "factory_blocks:hex"),
    ("C", "gears lower-left", 192, 100, 164, "factory_blocks:gears"),
    ("C", "gears lower-right", 193, 100, 164, "factory_blocks:gears"),
    ("C", "gears upper-left", 192, 101, 164, "factory_blocks:gears"),
    ("C", "gears upper-right", 193, 101, 164, "factory_blocks:gears"),
    ("D", "stock metalbox control", 204, 100, 164, "factory_blocks:metalbox"),
    ("D", "stock piping control", 208, 100, 164, "factory_blocks:piping"),
)


def text_bytes(text: str) -> bytes:
    return (text.rstrip() + "\n").encode("utf-8")


def json_bytes(value: object) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")


def placements_tsv() -> bytes:
    lines = ["section\tlabel\tx\ty\tz\tblock"]
    lines.extend(
        f"{section}\t{label}\t{x}\t{y}\t{z}\t{block}"
        for section, label, x, y, z, block in PLACEMENTS
    )
    return text_bytes("\n".join(lines))


def build_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"scoreboard objectives add {OBJECTIVE} dummy",
        f"scoreboard players add #builds {OBJECTIVE} 1",
        f"function {NAMESPACE}:clear",
        "forceload add 160 160 223 191",
        "fill 160 99 160 211 99 168 minecraft:smooth_stone",
    ]
    for section, label, x, y, z, block in PLACEMENTS:
        lines.append(f"# {section}: {label}")
        lines.append(f"setblock {x} {y} {z} {block}")
    lines.extend(
        (
            f"function {NAMESPACE}:verify_immediate",
            f"schedule function {NAMESPACE}:verify_20t 20t replace",
            f"schedule function {NAMESPACE}:verify_100t 100t replace",
        )
    )
    return text_bytes("\n".join(lines))


def verify_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"scoreboard players set #failures {OBJECTIVE} 0",
        f"scoreboard players set #checked {OBJECTIVE} 0",
    ]
    for section, label, x, y, z, block in PLACEMENTS:
        lines.append(f"# {section}: {label}")
        lines.append(
            f"execute unless block {x} {y} {z} {block} run "
            f"scoreboard players add #failures {OBJECTIVE} 1"
        )
        lines.append(f"scoreboard players add #checked {OBJECTIVE} 1")
    lines.extend(
        (
            f"execute unless score #builds {OBJECTIVE} matches 1 run "
            f"scoreboard players add #failures {OBJECTIVE} 1",
            f"scoreboard players add #checked {OBJECTIVE} 1",
        )
    )
    return text_bytes("\n".join(lines))


def phase_function(phase: str, announce: bool) -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"function {NAMESPACE}:verify",
        f"scoreboard players operation #{phase}_failures {OBJECTIVE} = "
        f"#failures {OBJECTIVE}",
        f"scoreboard players operation #{phase}_checked {OBJECTIVE} = "
        f"#checked {OBJECTIVE}",
    ]
    if announce:
        payload = [
            {"text": f"Factory Blocks gallery {phase}: "},
            {"score": {"name": f"#{phase}_checked", "objective": OBJECTIVE}},
            {"text": " checks, "},
            {"score": {"name": f"#{phase}_failures", "objective": OBJECTIVE}},
            {"text": " failures"},
        ]
        lines.append("tellraw @a " + json.dumps(payload, separators=(",", ":")))
    return text_bytes("\n".join(lines))


def base_files() -> dict[Path, bytes]:
    function_root = Path(f"datapack/data/{NAMESPACE}/function")
    return {
        Path("placements.tsv"): placements_tsv(),
        Path("datapack/pack.mcmeta"): json_bytes(
            {
                "pack": {
                    "description": "ATM 1.2.0 Factory Blocks BlueMap gallery",
                    "pack_format": 48,
                }
            }
        ),
        Path("datapack/data/minecraft/tags/function/load.json"): json_bytes(
            {"values": [f"{NAMESPACE}:load"]}
        ),
        function_root / "load.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"scoreboard objectives add {OBJECTIVE} dummy\n"
            "forceload add 160 160 223 191"
        ),
        function_root / "clear.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"schedule clear {NAMESPACE}:verify_20t\n"
            f"schedule clear {NAMESPACE}:verify_100t\n"
            "fill 160 99 160 191 124 191 minecraft:air\n"
            "fill 192 99 160 223 124 191 minecraft:air"
        ),
        function_root / "build.mcfunction": build_function(),
        function_root / "verify.mcfunction": verify_function(),
        function_root / "verify_immediate.mcfunction": phase_function(
            "immediate", True
        ),
        function_root / "verify_20t.mcfunction": phase_function("20t", False),
        function_root / "verify_100t.mcfunction": phase_function("100t", True),
        function_root / "release.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"schedule clear {NAMESPACE}:verify_20t\n"
            f"schedule clear {NAMESPACE}:verify_100t\n"
            "forceload remove 160 160 223 191"
        ),
    }


def sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def generated_files() -> dict[Path, bytes]:
    files = base_files()
    checksum = "".join(
        f"{sha256(files[path])}  {path.as_posix()}\n" for path in sorted(files)
    )
    files[Path("SHA256SUMS")] = checksum.encode("ascii")
    return files


def write_or_check(check: bool) -> int:
    failures: list[str] = []
    files = generated_files()
    for relative, payload in files.items():
        path = ROOT / relative
        if check:
            if not path.is_file():
                failures.append(f"missing generated file: {relative}")
            elif path.read_bytes() != payload:
                failures.append(f"generated file differs: {relative}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(payload)
    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    action = "checked" if check else "wrote"
    print(f"{action} {len(files)} deterministic gallery files")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
