# Generated by gallery/generate.py; do not edit.
scoreboard objectives add fb_gallery dummy
scoreboard players add #builds fb_gallery 1
function factory_blocks_gallery:clear
forceload add 160 160 223 191
fill 160 99 160 211 99 168 minecraft:smooth_stone
# A: isolated factory
setblock 164 100 164 factory_blocks:factory
# A: factory wall lower-left
setblock 168 100 164 factory_blocks:factory
# A: factory wall lower-edge
setblock 169 100 164 factory_blocks:factory
# A: factory wall lower-right
setblock 170 100 164 factory_blocks:factory
# A: factory wall left-edge
setblock 168 101 164 factory_blocks:factory
# A: factory wall center
setblock 169 101 164 factory_blocks:factory
# A: factory wall right-edge
setblock 170 101 164 factory_blocks:factory
# A: factory wall upper-left
setblock 168 102 164 factory_blocks:factory
# A: factory wall upper-edge
setblock 169 102 164 factory_blocks:factory
# A: factory wall upper-right
setblock 170 102 164 factory_blocks:factory
# B: hex south role 1
setblock 180 102 164 factory_blocks:hex
# B: hex south role 2
setblock 181 102 164 factory_blocks:hex
# B: hex south role 3
setblock 182 102 164 factory_blocks:hex
# B: hex south role 4
setblock 180 103 164 factory_blocks:hex
# B: hex south role 5
setblock 181 103 164 factory_blocks:hex
# B: hex south role 6
setblock 182 103 164 factory_blocks:hex
# B: hex south role 7
setblock 180 104 164 factory_blocks:hex
# B: hex south role 8
setblock 181 104 164 factory_blocks:hex
# B: hex south role 9
setblock 182 104 164 factory_blocks:hex
# C: gears lower-left
setblock 192 100 164 factory_blocks:gears
# C: gears lower-right
setblock 193 100 164 factory_blocks:gears
# C: gears upper-left
setblock 192 101 164 factory_blocks:gears
# C: gears upper-right
setblock 193 101 164 factory_blocks:gears
# D: stock metalbox control
setblock 204 100 164 factory_blocks:metalbox
# D: stock piping control
setblock 208 100 164 factory_blocks:piping
function factory_blocks_gallery:verify_immediate
schedule function factory_blocks_gallery:verify_20t 20t replace
schedule function factory_blocks_gallery:verify_100t 100t replace
