# Generated by gallery/generate.py; do not edit.
schedule clear factory_blocks_gallery:verify_20t
schedule clear factory_blocks_gallery:verify_100t
fill 160 99 160 191 124 191 minecraft:air
fill 192 99 160 223 124 191 minecraft:air
