# Generated by gallery/generate.py; do not edit.
function factory_blocks_gallery:verify
scoreboard players operation #immediate_failures fb_gallery = #failures fb_gallery
scoreboard players operation #immediate_checked fb_gallery = #checked fb_gallery
tellraw @a [{"text":"Factory Blocks gallery immediate: "},{"score":{"name":"#immediate_checked","objective":"fb_gallery"}},{"text":" checks, "},{"score":{"name":"#immediate_failures","objective":"fb_gallery"}},{"text":" failures"}]
