# Generated by gallery/generate.py; do not edit.
function factory_blocks_gallery:verify
scoreboard players operation #100t_failures fb_gallery = #failures fb_gallery
scoreboard players operation #100t_checked fb_gallery = #checked fb_gallery
tellraw @a [{"text":"Factory Blocks gallery 100t: "},{"score":{"name":"#100t_checked","objective":"fb_gallery"}},{"text":" checks, "},{"score":{"name":"#100t_failures","objective":"fb_gallery"}},{"text":" failures"}]
