# Generated by gallery/generate.py; do not edit.
scoreboard players set #failures fb_gallery 0
scoreboard players set #checked fb_gallery 0
# A: isolated factory
execute unless block 164 100 164 factory_blocks:factory run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# A: factory wall lower-left
execute unless block 168 100 164 factory_blocks:factory run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# A: factory wall lower-edge
execute unless block 169 100 164 factory_blocks:factory run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# A: factory wall lower-right
execute unless block 170 100 164 factory_blocks:factory run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# A: factory wall left-edge
execute unless block 168 101 164 factory_blocks:factory run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# A: factory wall center
execute unless block 169 101 164 factory_blocks:factory run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# A: factory wall right-edge
execute unless block 170 101 164 factory_blocks:factory run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# A: factory wall upper-left
execute unless block 168 102 164 factory_blocks:factory run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# A: factory wall upper-edge
execute unless block 169 102 164 factory_blocks:factory run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# A: factory wall upper-right
execute unless block 170 102 164 factory_blocks:factory run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# B: hex south role 1
execute unless block 180 102 164 factory_blocks:hex run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# B: hex south role 2
execute unless block 181 102 164 factory_blocks:hex run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# B: hex south role 3
execute unless block 182 102 164 factory_blocks:hex run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# B: hex south role 4
execute unless block 180 103 164 factory_blocks:hex run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# B: hex south role 5
execute unless block 181 103 164 factory_blocks:hex run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# B: hex south role 6
execute unless block 182 103 164 factory_blocks:hex run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# B: hex south role 7
execute unless block 180 104 164 factory_blocks:hex run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# B: hex south role 8
execute unless block 181 104 164 factory_blocks:hex run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# B: hex south role 9
execute unless block 182 104 164 factory_blocks:hex run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# C: gears lower-left
execute unless block 192 100 164 factory_blocks:gears run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# C: gears lower-right
execute unless block 193 100 164 factory_blocks:gears run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# C: gears upper-left
execute unless block 192 101 164 factory_blocks:gears run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# C: gears upper-right
execute unless block 193 101 164 factory_blocks:gears run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# D: stock metalbox control
execute unless block 204 100 164 factory_blocks:metalbox run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
# D: stock piping control
execute unless block 208 100 164 factory_blocks:piping run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
execute unless score #builds fb_gallery matches 1 run scoreboard players add #failures fb_gallery 1
scoreboard players add #checked fb_gallery 1
