# Generated by gallery/generate.py; do not edit.
function factory_blocks_gallery:verify
scoreboard players operation #20t_failures fb_gallery = #failures fb_gallery
scoreboard players operation #20t_checked fb_gallery = #checked fb_gallery
